Repository neptune-mutual-blue/protocol, pull requests merged in 2022-09, with the labels that each got.

#130 Fix Cover contract ACL requirements
  contracts/core/lifecycle/Cover.sol
  util/extract/keys/template-ts.js
Labels: bug, security, rc2

#136 Fix risk of insufficient liquidity
  contracts/libraries/CoverUtilV1.sol
  test/specs/libraries/cover-util.spec.js
Labels: bug, security, rc2, open-zeppelin-audit

#157 Fixes Issue #142 - Parallel access control
  contracts/core/Protocol.sol
  test/specs/protocol/grant-role.spec.js
Labels: bug, confirmed, security, rc2, open-zeppelin-audit

#122 Added a feature to close a report
  contracts/core/governance/resolution/Finalization.sol
  contracts/core/governance/resolution/Resolvable.sol
  contracts/interfaces/IResolvable.sol
  test/specs/governance/close-report.spec.js
Labels: enhancement, consensus, rc2

#156 Fixes Issue #134 - Conflated staking pool reward balances
  contracts/libraries/StakingPoolLibV1.sol
Labels: bug, security, rc2, open-zeppelin-audit

#132 Fix unstake after finalization
  contracts/core/governance/resolution/Finalization.sol
  contracts/libraries/GovernanceUtilV1.sol
  contracts/libraries/ProtoUtilV1.sol
  contracts/libraries/ValidationLibV1.sol
  test/specs/governance/resolution/unstake-with-claim.spec.js
  test/specs/governance/resolution/unstake.spec.js
Labels: bug

#160 Fixes Issue #144 - Able to close non-empty staking pool
  contracts/pool/Staking/StakingPoolBase.sol
Labels: bug, confirmed, rc2, open-zeppelin-audit

#161 Fixes Issue #145 - Collision between constants
  contracts/libraries/StakingPoolCoreLibV1.sol
  contracts/libraries/StakingPoolLibV1.sol
  test/specs/governance/deps.js
  test/specs/libraries/deps.js
  test/specs/liquidity/delegates/deps.js
  test/specs/liquidity/engine/deps.js
  test/specs/liquidity/vault-factory/deps.js
  test/specs/pool/staking/deps.js
  test/specs/recoverable/deps.js
  util/composer/libs.js
  util/key.js
Labels: bug, confirmed, rc2, open-zeppelin-audit

#163 Fixes Issue #150 - Missing event parameter
  contracts/interfaces/IStakingPools.sol
  contracts/pool/Staking/StakingPoolBase.sol
Labels: bug, confirmed, rc2, open-zeppelin-audit

#164 Fixes Issue #148 - Incorrect NPM threshold
  contracts/libraries/ProtoUtilV1.sol
  test/stories/1. policy.spec.js
Labels: bug, confirmed, rc2, open-zeppelin-audit

#166 Fixes Issue #154 - Incorrect individual liquidity share
  contracts/libraries/VaultLibV1.sol
Labels: bug, confirmed, rc2, open-zeppelin-audit

#167 Fixes Issue #147 - Imprecise bounds
  contracts/libraries/RoutineInvokerLibV1.sol
  contracts/libraries/StakingPoolLibV1.sol
  contracts/libraries/ValidationLibV1.sol
  contracts/libraries/VaultLibV1.sol
Labels: bug, confirmed, rc2, open-zeppelin-audit

#170 Fixes Issue #169 - Repeated pause validation
  contracts/core/Protocol.sol
Labels: confirmed, rc2, open-zeppelin-audit

#165 Fixes Issue #153 - The info parameter might lose information about an IPFS hash
  contracts/core/governance/Reporter.sol
  contracts/core/lifecycle/Cover.sol
  contracts/interfaces/ICover.sol
  contracts/interfaces/IReporter.sol
  contracts/libraries/CoverLibV1.sol
  contracts/libraries/StoreKeyUtil.sol
  util/composer/covers.js
  util/ipfs.js
Labels: enhancement, confirmed, rc2, open-zeppelin-audit

#159 Fixes Issue #141 - Incorrect policy fee
  contracts/core/cxToken/cxToken.sol
  contracts/libraries/PolicyHelperV1.sol
  test/examples/distributor/deps.js
  test/specs/cx-token-factory/deps.js
  test/specs/cx-token/deps.js
  test/specs/governance/deps.js
  test/specs/governance/resolution/deps.js
  test/specs/libraries/deps.js
  test/specs/lifecycle/cover-reassurance/deps.js
  test/specs/lifecycle/cover-stake/deps.js
  test/specs/lifecycle/cover/deps.js
  test/specs/liquidity/delegates/deps.js
  test/specs/liquidity/strategy/deps.js
  test/specs/liquidity/vault/deps.js
  test/specs/policy/calculate-policy-fee.spec.js
  test/specs/policy/deps.js
  util/composer/libs.js
  util/cxToken.js
Labels: bug, security, rc2, open-zeppelin-audit

#168 Fixes Issue #155 - Variable outside store
  contracts/core/policy/Policy.sol
  contracts/examples/NpmDistributor.sol
  contracts/interfaces/IPolicy.sol
  contracts/libraries/CoverUtilV1.sol
  contracts/libraries/PolicyHelperV1.sol
  contracts/libraries/ProtoUtilV1.sol
  fuzzing/CoverSpec.sol
  test/bdd/fractionalization.js
  test/examples/distributor/deps.js
  test/specs/cx-token/before-token-transfer.spec.js
  test/specs/cx-token/burn.spec.js
  test/specs/cx-token/ctor-vfns.spec.js
  test/specs/cx-token/deps.js
  test/specs/cx-token/get-coverage-starts-from.spec.js
  test/specs/cx-token/mint.spec.js
  test/specs/governance/deps.js
  test/specs/governance/resolution/deps.js
  test/specs/libraries/cover-util.spec.js
  test/specs/libraries/deps.js
  test/specs/lifecycle/cover-reassurance/capitalize-pool.spec.js
  test/specs/lifecycle/cover-reassurance/deps.js
  test/specs/lifecycle/cover-stake/ctor-vfns.spec.js
  test/specs/lifecycle/cover-stake/decrease-stake.spec.js
  test/specs/lifecycle/cover-stake/increase-stake.spec.js
  test/specs/lifecycle/cover-stake/stake-of.spec.js
  test/specs/lifecycle/cover/deps.js
  test/specs/liquidity/strategy/deps.js
  test/specs/liquidity/vault/deps.js
  test/specs/policy/calculate-policy-fee.spec.js
  test/specs/policy/ctor.spec.js
  test/specs/policy/get-cxtoken-by-expiry-date.spec.js
  test/specs/policy/purchase-cover.spec.js
  test/stories/1. policy.spec.js
  test/stories/2. governance.spec.js
  test/stories/5.coverage.claim.spec.js
  util/composer/initializer.js
Labels: enhancement, rc2, open-zeppelin-audit

#173 Fixes Issue #152 - Protocol administrator needs to handle external tokens
  contracts/pool/Bond/BondPoolBase.sol
  contracts/pool/Staking/StakingPoolBase.sol
Labels: enhancement, security, rc2, open-zeppelin-audit

#172 Fixes Issue #149 - Lack of input validation
  .vscode/settings.json
  contracts/core/Protocol.sol
  contracts/core/delegates/VaultDelegateBase.sol
  contracts/core/governance/resolution/Unstakable.sol
  contracts/core/policy/PolicyAdmin.sol
  contracts/interfaces/IPolicyAdmin.sol
  contracts/interfaces/IProtocol.sol
  contracts/interfaces/IUnstakable.sol
  contracts/libraries/GovernanceUtilV1.sol
  fuzzing/CoverSpec.sol
  test/examples/distributor/deps.js
  test/specs/cx-token-factory/deps.js
  test/specs/cx-token/deps.js
  test/specs/governance/deps.js
  test/specs/governance/resolution/deps.js
  test/specs/libraries/deps.js
  test/specs/lifecycle/cover-reassurance/deps.js
  test/specs/lifecycle/cover-stake/deps.js
  test/specs/lifecycle/cover/deps.js
  test/specs/lifecycle/cover/initialize.spec.js
  test/specs/liquidity/delegates/deps.js
  test/specs/liquidity/engine/deps.js
  test/specs/liquidity/strategy/deps.js
  test/specs/liquidity/vault-factory/deps.js
  test/specs/liquidity/vault/deps.js
  test/specs/policy-admin/deps.js
  test/specs/policy-admin/set-policy-rates.spec.js
  test/specs/policy/deps.js
  test/specs/pool/bond/deps.js
  test/specs/pool/staking/deps.js
  test/specs/protocol/add-contract.spec.js
  test/specs/protocol/add-member.spec.js
  test/specs/protocol/ctor-vfns.spec.js
  test/specs/protocol/grant-role.spec.js
  test/specs/protocol/pause.spec.js
  test/specs/protocol/remove-member.spec.js
  test/specs/protocol/setup-role.spec.js
  test/specs/protocol/unpause.spec.js
  test/specs/protocol/upgrade-contract.spec.js
  test/specs/recoverable/deps.js
  util/composer/initializer.js
Labels: bug, confirmed, rc2, open-zeppelin-audit

#185 Fixes Issue #181 - Unnecessary complex code
  contracts/libraries/CoverLibV1.sol
  contracts/libraries/StrategyLibV1.sol
Labels: confirmed, rc2, open-zeppelin-audit

#183 Fixes Issue #176 - Duplicate modifier
  contracts/core/ProtoBase.sol
Labels: confirmed, rc2, open-zeppelin-audit

#184 Fixes Issue #182 - Unnecessary coupling
  contracts/libraries/GovernanceUtilV1.sol
Labels: confirmed, rc2, open-zeppelin-audit

#187 Fixes Issue #174 - transfer and send calls are no longer considered best practice
  contracts/core/store/StoreBase.sol
  contracts/core/token/WithRecovery.sol
  contracts/libraries/BaseLibV1.sol
Labels: enhancement, rc2, open-zeppelin-audit

#186 Fixes Issue #178 - Incomplete deletion
  contracts/core/governance/resolution/Finalization.sol
Labels: rc2, open-zeppelin-audit

#189 Fixes Issue #180 - Misleading comments
  contracts/core/Protocol.sol
  contracts/core/governance/resolution/Finalization.sol
  contracts/libraries/AccessControlLibV1.sol
Labels: bug, confirmed, rc2, open-zeppelin-audit

#192 Fixed Deployment Issues
  examples/index.js
  util/composer/covers.js
  util/composer/initializer.js
  util/composer/pod-staking.js
  util/demo-data/add-liquidity.js
  util/demo-data/add-reassurance.js
  util/demo-data/purchase-policy.js
Labels: bug, deployment, javascript, non solidity, rc3/beta-release

#193 Updated config and few tests
  foundry.toml
  test/specs/cx-token/get-claimable-policy-of.spec.js
  test/specs/libraries/cover-util.spec.js
  test/specs/policy/get-cover-fee-info.spec.js
  util/extract/abis/index.js
Labels: test
